### ISSUE TITLE
arduino nano

### ISSUE THREAD

**Issue by DJDC13** [AlanChatham/UnoJoy#32]
I understand this has been answered before and you cant use this unojoy on the arduino nano as it has not got the ftdi chip for USB coms, is it possible to flash the little ftdi boards you get that are used to program the pro mini? Basically having that connected to a pro mini or nano but using the extra board as the USB link to the pc?

Thanks
Don

**Comment by AlanChatham** [comment]
This wouldn't be possible, since the USB firmware is actually running off the Atmel USB chip that's on board the Uno, and not the FTDI chip that was used in older Arduino generations. So, if you had/made a serial->USB converter that was based on the ATmega8u2 or 16u2, you could reprogram that, but the FTDI chip is a different animal. Sorry!
