### ISSUE TITLE
Not an issue but question before i start. am i still able to use serial communication after changing the arduino to controller mode or would i need to use another one?

### ISSUE THREAD

**Issue by KnifeOfDunwall** [AlanChatham/UnoJoy#46]

**Comment by AlanChatham** [comment]
Hi! Sorry I didn't get around to answering this earlier, but yes, you would pretty much have to set up another Arduino, or some other way to send Serial data to your PC, and since UnoJoy uses the Arduino's built-in serial port, you'd also have to run software serial on some pins, or some other communications protocol, like I2C, between the two.

Technically, you could go super deep into creating a new USB header and device that was a multi-class device that's both a game controller and a USB serial port, and figuring out a new way of sending data from the Arduino main chip to the ATmega8u2 communications chip, but that would basically be an entire new project at that point.
