### ISSUE TITLE
SOME UNOJOY (uno board) Q's.. 2022  Plz. help!

### ISSUE THREAD

**Issue by nimdinu** [AlanChatham/UnoJoy#49]
🔴 I have some questions about **UNOJOY** with **_ARDUINO UNO_** board.

A) Can I send 10bit analogue axis data to PC ?
B) Can I get more input pins like megajoy ? 
        ( physically with Button array or Keypad can extend the input pins of Arduino Uno)
        * 12 digital inputs not enough.
        * try to edit source (Unojoy.h) files to add more pins but it didn't work. 
C) Is it possible get PC data output to arduino ?
       * For use to display speed, gears or hypic feedback 
D) Can I use ESP Chip instead of Arduino?

If you know some ideas or new please Comment....

**Comment by AlanChatham** [comment]
I'm super sorry, I imagine this isn't very helpful coming a year later, but to answer your questions:

**A)** - MegaJoy actually uses 10 bit analog axis data, UnoJoy only uses 8 because it's designed to spoof a PS3 controller, so it was limited to what's there on a DualShock 3. This is handy because -

**B)** - You can actually just use the MegaJoy firmware on an Arduino Uno, since MegaJoy only creates a different logical USB controller than UnoJoy, with more buttons and stuff you can assign in the code.

**C)** - I'm sure it's technically possible, but would require a pretty hefty amount of work to add that channel. I don't know anything about force feedback and if there are open standards on that sort of stuff, and so it's not something that I plan on implementing

**D)** - UnoJoy and its variants all rely on code running on the Atmel chipsets, mostly the ATmega8U2 that's used as a serial-USB converter, and as such, the project isn't capable of working with the ESP boards, since they don't use this particular USB chip solution
